"""
QSS stylesheet generator for Material Design 3.

Generates a Qt Style Sheet string from a :class:`~koo2.ui.theme.palette.Palette`
and :class:`~koo2.ui.theme.typography.Typography` instance, giving all
standard Qt widgets an MD3-consistent look without external CSS frameworks.

Usage::

    from koo2.ui.theme.palette import DEFAULT_LIGHT
    from koo2.ui.theme.typography import DEFAULT_TYPOGRAPHY
    from koo2.ui.theme.stylesheet import build_stylesheet

    app.setStyleSheet(build_stylesheet(DEFAULT_LIGHT, DEFAULT_TYPOGRAPHY))
"""
from __future__ import annotations

from koo2.ui.theme.palette import DEFAULT_LIGHT, Palette
from koo2.ui.theme.typography import DEFAULT_TYPOGRAPHY, Typography


def _hex_with_alpha(hex_color: str, alpha: float) -> str:
    """Convert ``#RRGGBB`` + float alpha → ``rgba(r,g,b,a)``."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def build_stylesheet(
    palette: Palette = DEFAULT_LIGHT,
    typography: Typography = DEFAULT_TYPOGRAPHY,
) -> str:
    """Return a complete QSS string for the given *palette* and *typography*."""
    p = palette
    t = typography
    hover_layer = _hex_with_alpha(p.primary.color, p.hover_state_layer_opacity)
    pressed_layer = _hex_with_alpha(p.primary.color, p.pressed_state_layer_opacity)

    return f"""
/* ===================================================================
   koo2 Material Design 3 stylesheet
   Generated by koo2.ui.theme.stylesheet.build_stylesheet()
   =================================================================== */

/* --- Base ---------------------------------------------------------- */
QWidget {{
    background-color: {p.surface};
    color: {p.on_surface};
    font-family: {t.body_medium.family};
    font-size: {t.body_medium.size}px;
    font-weight: {t.body_medium.weight};
    outline: none;
    border: none;
}}

QMainWindow, QDialog {{
    background-color: {p.background};
}}

/* --- Buttons ------------------------------------------------------- */
QPushButton {{
    background-color: {p.primary.color};
    color: {p.primary.on_color};
    border: none;
    border-radius: 20px;
    padding: 10px 24px;
    font-size: {t.label_large.size}px;
    font-weight: {t.label_large.weight};
    min-height: 40px;
}}

QPushButton:hover {{
    background-color: {hover_layer};
    border: 1px solid {p.primary.color};
    color: {p.primary.color};
}}

QPushButton:pressed {{
    background-color: {pressed_layer};
}}

QPushButton:disabled {{
    background-color: {_hex_with_alpha(p.on_surface, 0.12)};
    color: {_hex_with_alpha(p.on_surface, 0.38)};
}}

QPushButton[flat="true"] {{
    background-color: transparent;
    color: {p.primary.color};
    border: none;
}}

QPushButton[outlined="true"] {{
    background-color: transparent;
    color: {p.primary.color};
    border: 1px solid {p.outline};
}}

QPushButton[outlined="true"]:hover {{
    background-color: {hover_layer};
}}

/* --- Text fields / Line edits ------------------------------------- */
QLineEdit {{
    background-color: {p.surface_variant};
    color: {p.on_surface};
    border: none;
    border-bottom: 1px solid {p.outline};
    border-radius: 4px 4px 0 0;
    padding: 16px 16px 4px 16px;
    font-size: {t.body_large.size}px;
    min-height: 56px;
    selection-background-color: {p.primary_container};
    selection-color: {p.on_primary_container};
}}

QLineEdit:focus {{
    border-bottom: 2px solid {p.primary.color};
    background-color: {p.surface_variant};
}}

QLineEdit:disabled {{
    color: {_hex_with_alpha(p.on_surface, 0.38)};
    border-bottom-color: {_hex_with_alpha(p.on_surface, 0.38)};
}}

QLineEdit[readOnly="true"] {{
    background-color: transparent;
    border-bottom: 1px dashed {p.outline_variant};
}}

/* --- Text areas ---------------------------------------------------- */
QTextEdit, QPlainTextEdit {{
    background-color: {p.surface_variant};
    color: {p.on_surface};
    border: 1px solid {p.outline};
    border-radius: 4px;
    padding: 8px;
    font-size: {t.body_large.size}px;
    selection-background-color: {p.primary_container};
    selection-color: {p.on_primary_container};
}}

QTextEdit:focus, QPlainTextEdit:focus {{
    border: 2px solid {p.primary.color};
}}

/* --- ComboBox (Select / Dropdown) ---------------------------------- */
QComboBox {{
    background-color: {p.surface_variant};
    color: {p.on_surface};
    border: none;
    border-bottom: 1px solid {p.outline};
    border-radius: 4px 4px 0 0;
    padding: 8px 40px 8px 16px;
    font-size: {t.body_large.size}px;
    min-height: 40px;
}}

QComboBox:focus {{
    border-bottom: 2px solid {p.primary.color};
}}

QComboBox::drop-down {{
    border: none;
    width: 40px;
}}

QComboBox::down-arrow {{
    width: 18px;
    height: 18px;
}}

QComboBox QAbstractItemView {{
    background-color: {p.surface};
    color: {p.on_surface};
    border: 1px solid {p.outline_variant};
    border-radius: 4px;
    selection-background-color: {p.primary_container};
    selection-color: {p.on_primary_container};
    padding: 8px;
}}

/* --- Spinbox ------------------------------------------------------- */
QSpinBox, QDoubleSpinBox {{
    background-color: {p.surface_variant};
    color: {p.on_surface};
    border: none;
    border-bottom: 1px solid {p.outline};
    border-radius: 4px 4px 0 0;
    padding: 8px 8px 4px 16px;
    min-height: 40px;
    font-size: {t.body_large.size}px;
}}

QSpinBox:focus, QDoubleSpinBox:focus {{
    border-bottom: 2px solid {p.primary.color};
}}

/* --- CheckBox ----------------------------------------------------- */
QCheckBox {{
    color: {p.on_surface};
    spacing: 8px;
    font-size: {t.body_medium.size}px;
}}

QCheckBox::indicator {{
    width: 18px;
    height: 18px;
    border: 2px solid {p.outline};
    border-radius: 2px;
    background-color: transparent;
}}

QCheckBox::indicator:checked {{
    background-color: {p.primary.color};
    border-color: {p.primary.color};
}}

QCheckBox::indicator:hover {{
    border-color: {p.primary.color};
}}

/* --- RadioButton --------------------------------------------------- */
QRadioButton {{
    color: {p.on_surface};
    spacing: 8px;
    font-size: {t.body_medium.size}px;
}}

QRadioButton::indicator {{
    width: 20px;
    height: 20px;
    border: 2px solid {p.outline};
    border-radius: 10px;
    background-color: transparent;
}}

QRadioButton::indicator:checked {{
    border-color: {p.primary.color};
    background-color: {p.primary.color};
}}

/* --- Labels ------------------------------------------------------- */
QLabel {{
    background-color: transparent;
    color: {p.on_surface};
    font-size: {t.body_medium.size}px;
    padding: 0;
    border: none;
}}

QLabel[heading="true"] {{
    font-size: {t.headline_small.size}px;
    font-weight: {t.headline_small.weight};
    color: {p.on_background};
}}

QLabel[title="true"] {{
    font-size: {t.title_large.size}px;
    font-weight: {t.title_large.weight};
    color: {p.on_background};
}}

QLabel[caption="true"] {{
    font-size: {t.body_small.size}px;
    color: {p.on_surface_variant};
}}

/* --- Tab Widget ---------------------------------------------------- */
QTabWidget::pane {{
    border: 1px solid {p.outline_variant};
    border-radius: 0 0 4px 4px;
    background-color: {p.surface};
}}

QTabBar::tab {{
    background-color: transparent;
    color: {p.on_surface_variant};
    padding: 12px 24px;
    border-bottom: 2px solid transparent;
    font-size: {t.title_small.size}px;
    font-weight: {t.title_small.weight};
}}

QTabBar::tab:selected {{
    color: {p.primary.color};
    border-bottom: 2px solid {p.primary.color};
}}

QTabBar::tab:hover:!selected {{
    color: {p.on_surface};
    background-color: {hover_layer};
}}

/* --- Table / Tree View --------------------------------------------- */
QTableView, QTreeView, QListView {{
    background-color: {p.surface};
    color: {p.on_surface};
    border: 1px solid {p.outline_variant};
    border-radius: 4px;
    alternate-background-color: {p.surface_variant};
    gridline-color: {p.outline_variant};
    selection-background-color: {p.primary_container};
    selection-color: {p.on_primary_container};
    font-size: {t.body_medium.size}px;
}}

QHeaderView::section {{
    background-color: {p.surface_variant};
    color: {p.on_surface_variant};
    padding: 8px 12px;
    border: none;
    border-right: 1px solid {p.outline_variant};
    border-bottom: 1px solid {p.outline_variant};
    font-size: {t.label_medium.size}px;
    font-weight: {t.label_medium.weight};
}}

QHeaderView::section:horizontal:first {{
    border-top-left-radius: 4px;
}}

QTableView::item, QTreeView::item, QListView::item {{
    padding: 8px 12px;
    min-height: 40px;
    border-bottom: 1px solid {p.outline_variant};
}}

QTableView::item:selected, QTreeView::item:selected, QListView::item:selected {{
    background-color: {p.primary_container};
    color: {p.on_primary_container};
}}

QTableView::item:hover, QTreeView::item:hover, QListView::item:hover {{
    background-color: {hover_layer};
}}

/* --- Scroll bars --------------------------------------------------- */
QScrollBar:vertical {{
    background-color: transparent;
    width: 8px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background-color: {p.outline_variant};
    border-radius: 4px;
    min-height: 32px;
    margin: 0 1px;
}}

QScrollBar::handle:vertical:hover {{
    background-color: {p.outline};
}}

QScrollBar:horizontal {{
    background-color: transparent;
    height: 8px;
    margin: 0;
}}

QScrollBar::handle:horizontal {{
    background-color: {p.outline_variant};
    border-radius: 4px;
    min-width: 32px;
    margin: 1px 0;
}}

QScrollBar::handle:horizontal:hover {{
    background-color: {p.outline};
}}

QScrollBar::add-line, QScrollBar::sub-line {{
    width: 0;
    height: 0;
}}

/* --- Toolbar ------------------------------------------------------- */
QToolBar {{
    background-color: {p.surface};
    border-bottom: 1px solid {p.outline_variant};
    spacing: 4px;
    padding: 4px 8px;
}}

QToolButton {{
    background-color: transparent;
    color: {p.on_surface_variant};
    border: none;
    border-radius: 20px;
    padding: 8px;
    font-size: {t.label_large.size}px;
}}

QToolButton:hover {{
    background-color: {hover_layer};
    color: {p.primary.color};
}}

QToolButton:pressed {{
    background-color: {pressed_layer};
}}

/* --- Menu bar / Menu ---------------------------------------------- */
QMenuBar {{
    background-color: {p.surface};
    color: {p.on_surface};
    padding: 4px 0;
    border-bottom: 1px solid {p.outline_variant};
    font-size: {t.body_medium.size}px;
}}

QMenuBar::item {{
    padding: 8px 12px;
    background-color: transparent;
}}

QMenuBar::item:selected {{
    background-color: {hover_layer};
    color: {p.primary.color};
    border-radius: 4px;
}}

QMenu {{
    background-color: {p.surface};
    color: {p.on_surface};
    border: 1px solid {p.outline_variant};
    border-radius: 4px;
    padding: 8px 0;
}}

QMenu::item {{
    padding: 10px 16px;
    font-size: {t.body_medium.size}px;
}}

QMenu::item:selected {{
    background-color: {p.primary_container};
    color: {p.on_primary_container};
}}

QMenu::separator {{
    height: 1px;
    background-color: {p.outline_variant};
    margin: 4px 0;
}}

/* --- Status bar ---------------------------------------------------- */
QStatusBar {{
    background-color: {p.surface};
    color: {p.on_surface_variant};
    border-top: 1px solid {p.outline_variant};
    font-size: {t.body_small.size}px;
}}

/* --- Tooltip ------------------------------------------------------- */
QToolTip {{
    background-color: {p.on_surface};
    color: {p.surface};
    border: none;
    border-radius: 4px;
    padding: 4px 8px;
    font-size: {t.body_small.size}px;
}}

/* --- Splitter ------------------------------------------------------ */
QSplitter::handle {{
    background-color: {p.outline_variant};
    width: 1px;
    height: 1px;
}}

/* --- Progress bar -------------------------------------------------- */
QProgressBar {{
    background-color: {p.surface_variant};
    border: none;
    border-radius: 4px;
    height: 4px;
    text-align: center;
    color: transparent;
}}

QProgressBar::chunk {{
    background-color: {p.primary.color};
    border-radius: 4px;
}}

/* --- Group box ----------------------------------------------------- */
QGroupBox {{
    border: 1px solid {p.outline_variant};
    border-radius: 4px;
    margin-top: 20px;
    padding: 12px;
    font-size: {t.label_large.size}px;
    font-weight: {t.label_large.weight};
    color: {p.on_surface_variant};
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 8px;
    color: {p.on_surface_variant};
    background-color: {p.surface};
}}
"""


def apply_to_app(
    app: object,
    palette: Palette = DEFAULT_LIGHT,
    typography: Typography = DEFAULT_TYPOGRAPHY,
) -> None:
    """Apply the Material Design stylesheet to a ``QApplication``."""
    app.setStyleSheet(build_stylesheet(palette, typography))  # type: ignore[attr-defined]
